### PR TITLE
No current directory (".") in @INC since perl v5.26

### PR DESCRIPTION
**Pull request by while0pass**
https://perldoc.perl.org/perl5260delta

### CODE REVIEW

**Comment by while0pass** [comment]
```out
$ perl Makefile.PL
Generating collation tailoring for Church Slavonic...
do "mklocale.pl" failed, '.' is no longer in @INC; did you mean do "./mklocale.pl"? at Makefile.PL line 11.
couldn't do mklocale.pl: No such file or directory at Makefile.PL line 13.
$  perl -V | head -1
Summary of my perl5 (revision 5 version 30 subversion 0) configuration:
```

**Comment by while0pass** [comment]
@typiconman Please, check the pull request to harmonize repo with perl v5.26 and above.

**Review by typiconman — APPROVED** [review]
LGTM

**Comment by typiconman** [comment]
Merged, thank you!

**Pull request merged**
